import type { Metadata } from 'next'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <h2>path: app / layout.js</h2>
        <AntdRegistry>
          {children}
          {modal}
          <div id="modal-root"></div>
        </AntdRegistry>
      </body>
    </html>
  )
}
